CREATE TABLE IF NOT EXISTS todos (
    itemId INT AUTO_INCREMENT PRIMARY KEY,
    uid INT NOT NULL,
    itemName VARCHAR(255) NOT NULL,
    description TEXT,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    itemDeadline TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    needCheckInDays INT
);

-- CREATE TABLE users (
--     uid INT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(50) UNIQUE NOT NULL,
--     password_hash VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
