CREATE TABLE IF NOT EXISTS todos (
    itemId INT AUTO_INCREMENT PRIMARY KEY,
    uid INT NOT NULL,
    itemName VARCHAR(255) NOT NULL,
    description TEXT,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    itemDeadline TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    needCheckInDays INT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    uid INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
